# Generated by Django 2.2.10 on 2021-08-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_start', models.DateField(auto_now=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'ordering': ('date_start',),
            },
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'PollAnswer',
                'verbose_name_plural': 'PollAnswers',
                'ordering': ('question',),
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_user_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('text_answer', models.TextField()),
                ('choice_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_polls_2_app.PollAnswer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserAnswer',
                'verbose_name_plural': 'UserAnswers',
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='PollsAssignedToUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_polls_2_app.Poll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PollsAssignedToUsers',
                'verbose_name_plural': 'PollsAssignedToUsers',
                'ordering': ('poll',),
            },
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'CheckBox'), ('2', 'Choice'), ('3', 'Text')], max_length=255)),
                ('text', models.TextField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_polls_2_app.Poll')),
            ],
            options={
                'verbose_name': 'PollQuestion',
                'verbose_name_plural': 'PollQuestions',
                'ordering': ('poll',),
            },
        ),
        migrations.AddField(
            model_name='pollanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_polls_2_app.PollQuestion'),
        ),
    ]
