# Generated by Django 2.2.10 on 2021-08-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_polls_2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('id', 'date_start'), 'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
    ]
