# Generated by Django 2.2.10 on 2021-09-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_polls_2_app', '0002_auto_20210826_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_start',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pollanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_variants', to='user_polls_2_app.PollQuestion'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user_polls_2_app.Poll'),
        ),
    ]
