# Generated by Django 3.2.7 on 2021-10-13 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_polls_2_app', '0002_rename_pollsassignedtousers_pollsassignedtouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_polls_2_app.pollquestion'),
            preserve_default=False,
        ),
    ]
