# Generated by Django 3.2.7 on 2021-10-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_polls_2_app', '0003_useranswer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollanswer',
            options={'verbose_name': 'PollAnswer', 'verbose_name_plural': 'PollAnswers'},
        ),
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'verbose_name': 'PollQuestion', 'verbose_name_plural': 'PollQuestions'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'UserAnswer', 'verbose_name_plural': 'UserAnswers'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='pollanswer',
            order_with_respect_to='question',
        ),
        migrations.AlterOrderWithRespectTo(
            name='pollquestion',
            order_with_respect_to='poll',
        ),
        migrations.AlterOrderWithRespectTo(
            name='useranswer',
            order_with_respect_to='question',
        ),
    ]
