# Generated by Django 3.2.7 on 2021-10-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_polls_2_app', '0004_auto_20211013_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='anonymous_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
