# Generated by Django 3.2.7 on 2021-10-25 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_polls_2_app', '0009_auto_20211025_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsassignedtouser',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
