# Generated by Django 2.2.10 on 2021-09-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, help_text='Please share your contact', max_length=255),
        ),
    ]
